
Basic Jupyter usage
=================


Humberto Ribeiro de Souza
First line of a Jupyter notebook

Shift-Enter: run a cell
Alt-Enter: Creates a new cell below
Plus sign: Adds a cell below

Tab after a dot: shows a pop-up of the methods on a given object E.g after np.
shift.tab show the docstring of the object E.g. after np.

ESC: Command Mode for easy navigation between cells
 - While in Commad Mode:
   A insert a new cell above
   B insert a new cell below
   D D delete the current cell (D is twice)
   Shift Up and down por selecting multiple cells
   Shift+M to merge them
ESC + F: Find into your code but NOT into the outputs

When within a cell you want to split, use CTRL+SHIFT+ -  at the point you want to split the cell in two.
? Gets a help as help(item)

It is possible to debug with the magic command %pdb
** Text boxes do not need to have the comment # before

Accessible kernels (if available on the host computer):
%%bash
%%HTML
%%ruby
%%perl

Multicursor select feature:
In, lets say, an array, just select text holding the ALT key, then select the position, still holding the ALT key and insert a comma
a = [
    1,
    2,
    3,
    4,
    5,
    ]
    
Adding an extension for presentation
pip install RISE
Then
jupyter-nbextension install rise --py --sys-prefix
jupyter-nbextension enable rise --py --sys-prefix

"Big data" analysis

Solutions for processing or querying large data samples:

* ipyparallel (from ipython cluster)performs simple map-reduce operations in python. It makes possible training different models in parallel
* spark-sql magic %%sql
* pyspark

# Check if available somewhere:
# %%java
# <Java Commands>;


This is a markdown text cell

Basic numpy usage
=================

In [ ]:
# This is a code cell, single comment
'''
This is a comment often used for docstrings
'''

In [ ]:
import numpy as np

pylist = [1,2,3,4,5]
pylist

In [8]:
#This shows help for any function or object. It is actually a Python function
help(pylist)

Help on list object:

class list(object)
 |  list() -> new empty list
 |  list(iterable) -> new list initialized from iterable's items
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |  
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  __iter__(self, /)
 |      Implement iter(self).
 |  
 |  __le__(self, value, /

In [9]:
print("This is a Python 3.0 print command usage")

This is a Python 3.0 print command usage


In [10]:
np_array = np.array(pylist)
np_array #This will show the result when this cell is executed

array([1, 2, 3, 4, 5])

In [41]:
other_list = [100,101,102,103,104]

In [42]:
my_lists = [pylist, other_list]

In [43]:
my_lists

[[1, 2, 3, 4, 5], [100, 101, 102, 103, 104]]

In [44]:
my_new_array = np.array(my_lists)
my_new_array

array([[  1,   2,   3,   4,   5],
       [100, 101, 102, 103, 104]])

In [45]:
my_new_array.shape

(2, 5)

In [46]:
#calling windows command
!dir   

 Volume in drive D is Win-Data
 Volume Serial Number is D0C7-F7E1

 Directory of D:\uoft-work\jupyterNotebooks

2019-03-16  05:16 PM    <DIR>          .
2019-03-16  05:16 PM    <DIR>          ..
2019-03-16  01:38 PM    <DIR>          .ipynb_checkpoints
2019-03-16  05:16 PM            13,512 NumPy - Creating Arrays.ipynb
2019-03-16  01:34 PM                86 README.md
               2 File(s)         13,598 bytes
               3 Dir(s)  65,457,807,360 bytes free


In [47]:
my_new_array.dtype

dtype('int32')

In [49]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [50]:
zeroes_array=np.zeros(6)

In [51]:
zeroes_array.dtype

dtype('float64')

In [56]:
np.ones([6,6])

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [57]:
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [58]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [60]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [61]:
np.arange(6,36,3)

array([ 6,  9, 12, 15, 18, 21, 24, 27, 30, 33])

In [63]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

Arrays and scalars
===============

In [64]:
5/2  #OK if Python 3, otherwise use from __future__ import division

2.5

In [67]:
array1 = np.array([[1,2,3,4],[5,6,7,8]])

In [69]:
array1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [70]:
array1 * array1

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [71]:
array1 - array1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [73]:
1/array1  #radix of -1

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.2       , 0.16666667, 0.14285714, 0.125     ]])

In [74]:
array1**3  # exponential

array([[  1,   8,  27,  64],
       [125, 216, 343, 512]], dtype=int32)

Indexing Arrays
=============

In [76]:
array1 = np.arange(0,11)

In [78]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [81]:
array1[4]

4

In [82]:
array1[2:6]

array([2, 3, 4, 5])

In [83]:
array1[0:5]

array([0, 1, 2, 3, 4])

In [84]:
array1[0:6] = 11

In [85]:
array1

array([11, 11, 11, 11, 11, 11,  6,  7,  8,  9, 10])

In [88]:
array1 = np.arange(0,11) # reset it
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [92]:
sliced_array = array1[0:5]
sliced_array

array([0, 1, 2, 3, 4])

In [93]:
sliced_array[:] = 50
sliced_array

array([50, 50, 50, 50, 50])

In [94]:
array1 #notice that it is not a copy! 

array([50, 50, 50, 50, 50,  5,  6,  7,  8,  9, 10])

In [97]:
array1_copy = array1.copy()
array1_copy

array([50, 50, 50, 50, 50,  5,  6,  7,  8,  9, 10])

In [99]:
array1_copy[:5] = 12
array1_copy # Now it is a copy

array([12, 12, 12, 12, 12,  5,  6,  7,  8,  9, 10])

In [100]:
array1

array([50, 50, 50, 50, 50,  5,  6,  7,  8,  9, 10])

In [101]:
#Array 2D
array_2d = np.array(([1,2,3],[5,15,20],[30,33,36]))
array_2d

array([[ 1,  2,  3],
       [ 5, 15, 20],
       [30, 33, 36]])

In [103]:
array_2d[1]

array([ 5, 15, 20])

In [104]:
array_2d[0]

array([1, 2, 3])

In [105]:
array_2d[1][0]


5

In [107]:
array_2d[:2,1:] # first is lines , second is columns [col1:col2,line1:line2]

array([[ 2,  3],
       [15, 20]])

In [108]:
array_2d[2] #fancy indexing

array([30, 33, 36])

In [111]:
array_2d = np.zeros((5,5))
array_2d

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [113]:
array_length = array_2d.shape[1]
array_length

5

In [114]:
for i in range(array_length):
    array_2d[i] = 1
    
array_2d

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [115]:
for i in range(array_length):
    array_2d[i] = i
    
array_2d

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [118]:
for i in range(array_length):
    array_2d[1][i] = 10
    
array_2d

array([[ 0.,  0.,  0.,  0.,  0.],
       [10., 10., 10., 10., 10.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.]])

In [120]:
for i in range(array_length):
    array_2d[i][i] = 22
    
array_2d

array([[22.,  0.,  0.,  0.,  0.],
       [10., 22., 10., 10., 10.],
       [ 2.,  2., 22.,  2.,  2.],
       [ 3.,  3.,  3., 22.,  3.],
       [ 4.,  4.,  4.,  4., 22.]])

In [121]:
array_2d[[1,2,4]]

array([[10., 22., 10., 10., 10.],
       [ 2.,  2., 22.,  2.,  2.],
       [ 4.,  4.,  4.,  4., 22.]])

In [128]:
array_2d[[4,1,0]]

array([[ 4.,  4.,  4.,  4., 22.],
       [10., 22., 10., 10., 10.],
       [22.,  0.,  0.,  0.,  0.]])

Transposing Arrays
================

In [130]:
array1 = np.arange(30).reshape((10,3))
array1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [131]:
array1.T

array([[ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28],
       [ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29]])

In [132]:
np.dot(array1,array1.T)

array([[   5,   14,   23,   32,   41,   50,   59,   68,   77,   86],
       [  14,   50,   86,  122,  158,  194,  230,  266,  302,  338],
       [  23,   86,  149,  212,  275,  338,  401,  464,  527,  590],
       [  32,  122,  212,  302,  392,  482,  572,  662,  752,  842],
       [  41,  158,  275,  392,  509,  626,  743,  860,  977, 1094],
       [  50,  194,  338,  482,  626,  770,  914, 1058, 1202, 1346],
       [  59,  230,  401,  572,  743,  914, 1085, 1256, 1427, 1598],
       [  68,  266,  464,  662,  860, 1058, 1256, 1454, 1652, 1850],
       [  77,  302,  527,  752,  977, 1202, 1427, 1652, 1877, 2102],
       [  86,  338,  590,  842, 1094, 1346, 1598, 1850, 2102, 2354]])